[mypy]
python_version = 3.14
warn_return_any = False
warn_unused_configs = True
ignore_missing_imports = True

# Only check project Python files in root directory
files = *.py
exclude = (?x)(
    ^venv/
    | ^config/
    | ^documentation/
    | ^helm/
    | ^k8s/
    | ^stress-pod/
    | ^utils/
    | ^data/
    )
