[pytest]
# Only discover tests in root directory
testpaths = .
python_files = test_*.py
norecursedirs = venv .git __pycache__ config documentation helm k8s stress-pod utils data .ruff_cache
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
