apiVersion: batch/v1
kind: Job
metadata:
  name: stress-pod
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: stress-sa   # 👈 ADD THIS
      restartPolicy: Never
      containers:
        - name: stress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "{{ .Values.targetUrl }}"