apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stress-rolebinding
subjects:
  - kind: ServiceAccount
    name: stress-sa
roleRef:
  kind: Role
  name: stress-role
  apiGroup: rbac.authorization.k8s.io