{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "severus-ai.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "severus_sticky"
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | default "severus-ai.local" }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | default "severus-ai.local" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "severus-ai.fullname" . }}
                port:
{{- if .Values.certificates.enabled }}
                  number: 8080
{{- else }}
                  number: {{ .Values.service.port }}
{{- end }}
{{- end }}