apiVersion: v1
kind: Service
metadata:
  name: {{ include "severus-ai.fullname" . }}
  labels:
    app: severus-ai
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: severus-ai
  ports:
{{- if .Values.certificates.enabled }}
    - name: https-mtls
      port: 8501
      targetPort: 8501
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
{{- else }}
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8502
      protocol: TCP
{{- end }}
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP