{{- if .Values.stress.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: stress-pod
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: stress
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      restartPolicy: Never
      containers:
        - name: stress
          image: "{{ .Values.stress.image.repository }}:{{ .Values.stress.image.tag }}"
          imagePullPolicy: Always
{{- if .Values.certificates.enabled }}
          env:
            - name: CLIENT_CERT_PATH
              value: /etc/certs/tls.crt
            - name: CLIENT_KEY_PATH
              value: /etc/certs/tls.key
            - name: CA_BUNDLE_PATH
              value: /etc/certs/ca.crt
{{- end }}

          command: ["/bin/bash", "-c"]
          args:
            - |
              ./stress_pod.sh \
{{- range .Values.stress.args.targets }}
                -t {{ . }} \
{{- end }}
                -tr {{ .Values.stress.args.totalRequests }} \
                -c {{ .Values.stress.args.concurrency }} \
                -r {{ .Values.stress.args.runs }} \
                -s {{ .Values.stress.args.sleepSeconds }} \
{{- range .Values.stress.args.podLabels }}
                -p {{ . }} \
{{- end }}
{{- if .Values.certificates.enabled }}
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ .Values.certificates.clientCert.secretName }}
{{- end }}
{{- end }}
