{{- if .Values.stress.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: stress-pod
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: stress
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      restartPolicy: Never
      containers:
        - name: stress
          image: "{{ .Values.stress.image.repository }}:{{ .Values.stress.image.tag }}"
          imagePullPolicy: Always

          command: ["/bin/bash", "-c"]
          args:
            - |
              ./stress_pod.sh \
{{- range .Values.stress.args.targets }}
                -t {{ . }} \
{{- end }}
                -tr {{ .Values.stress.args.totalRequests }} \
                -c {{ .Values.stress.args.concurrency }} \
                -r {{ .Values.stress.args.runs }} \
                -s {{ .Values.stress.args.sleepSeconds }} \
{{- range .Values.stress.args.podLabels }}
                -p {{ . }} \
{{- end }}
{{- end }}
